language: node_js
sudo: false
node_js:
  - '6.11.1'

before_script: 
  - 'npm install -g gulp'
  - 'npm install -g electron'
  - 'npm install -g electron-prebuilt'
  - 'npm install -g electron-packager'
  - 'npm install -g electron-builder'
  - 'npm install'

after_script: 
  - 'gulp sass'
  - 'gulp compress'
  - 'gulp lint'