language: node_js
sudo: true
node_js:
  - '6.11.1'
before_install:
  - 'sudo add-apt-repository ppa:ubuntu-wine/ppa -y'
  - 'sudo apt-get update -y'
  - 'sudo apt-get install wine1.8 winetricks -y'
before_script: 
  - 'npm install -g gulp'
  - 'npm install -g electron'
  - 'npm install -g electron-prebuilt'
  - 'npm install -g electron-packager'
  - 'npm install -g electron-builder'
  - 'npm install'
after_script: 
  - 'gulp sass'
  - 'gulp compress'
  - 'gulp lint'