language: node_js
sudo: true
node_js:
  - '6.11.1'

before_script: 
  - 'add-apt-repository ppa:ubuntu-wine/ppa'
  - 'apt-get update'
  - 'apt-get install -y wine1.7'
  - 'npm install -g gulp'
  - 'npm install -g electron'
  - 'npm install -g electron-prebuilt'
  - 'npm install -g electron-packager'
  - 'npm install -g electron-builder'
  - 'npm install'

after_script: 
  - 'gulp sass'
  - 'gulp compress'
  - 'gulp lint'